import { StyleSheet } from "react-native";
import { ThemeColors } from "../../types";

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.cardBackground,
    },
    content: {
      padding: 20,
    },
    title: {
      fontSize: 24,
      fontWeight: "bold",
      marginBottom: 10,
      textAlign: "center",
      color: colors.text,
    },
    description: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 30,
      textAlign: "center",
      lineHeight: 20,
    },
    formContainer: {
      width: "100%",
    },
    label: {
      fontSize: 16,
      fontWeight: "500",
      marginBottom: 8,
      color: colors.text,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      marginBottom: 16,
      color: colors.text,
      backgroundColor: colors.inputBackground,
    },
    inputContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      paddingHorizontal: 12,
      backgroundColor: colors.inputBackground,
    },
    currencySymbol: {
      fontSize: 24,
      color: colors.textSecondary,
      marginRight: 8,
    },
    amountInput: {
      flex: 1,
      fontSize: 24,
      paddingVertical: 16,
      color: colors.text,
    },
    hint: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 8,
      marginBottom: 24,
    },
    button: {
      backgroundColor: colors.accent,
      paddingVertical: 16,
      paddingHorizontal: 32,
      borderRadius: 8,
      alignItems: "center",
      marginTop: 16,
    },
    buttonDisabled: {
      opacity: 0.5,
    },
    buttonText: {
      color: "#ffffff",
      fontSize: 16,
      fontWeight: "600",
    },
    secondaryButton: {
      paddingVertical: 12,
      alignItems: "center",
      marginTop: 8,
    },
    secondaryButtonText: {
      color: colors.accent,
      fontSize: 16,
    },
    warningContainer: {
      backgroundColor: colors.warningBackground,
      borderRadius: 8,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    warningText: {
      fontSize: 14,
      color: colors.text,
      textAlign: "center",
      lineHeight: 20,
    },
    errorText: {
      color: "#dc3545",
      fontSize: 14,
      textAlign: "center",
      marginBottom: 16,
    },
    successIcon: {
      fontSize: 64,
      textAlign: "center",
      color: colors.accent,
      marginBottom: 16,
    },
    errorIcon: {
      fontSize: 64,
      textAlign: "center",
      color: "#dc3545",
      marginBottom: 16,
    },
    infoContainer: {
      marginBottom: 24,
    },
    infoRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    infoLabel: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    infoValue: {
      fontSize: 14,
      fontWeight: "500",
      color: colors.text,
    },
    detailsContainer: {
      backgroundColor: colors.background,
      borderRadius: 8,
      padding: 16,
      marginBottom: 24,
      width: "100%",
      borderWidth: 1,
      borderColor: colors.border,
    },
    detailRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 8,
    },
    detailLabel: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    detailValue: {
      fontSize: 14,
      fontWeight: "500",
      color: colors.text,
    },
    otpHint: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 16,
    },
    disclaimer: {
      fontSize: 12,
      color: colors.textSecondary,
      textAlign: "center",
      marginTop: 16,
      lineHeight: 18,
    },
    applePayButton: {
      height: 48,
      marginTop: 16,
      marginBottom: 8,
    },
    phoneInputContainer: {
      flexDirection: "row",
      alignItems: "stretch",
      marginBottom: 16,
    },
    flagContainer: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      paddingVertical: 16,
      borderWidth: 1,
      borderColor: colors.border,
      borderTopLeftRadius: 8,
      borderBottomLeftRadius: 8,
      backgroundColor: colors.inputBackground,
      minHeight: 48,
      justifyContent: "center",
    },
    flagText: {
      fontSize: 16,
      marginRight: 4,
    },
    countryCode: {
      fontSize: 16,
      color: colors.text,
      fontWeight: "500",
    },
    phoneInput: {
      backgroundColor: colors.inputBackground,
      borderRadius: 0,
      borderTopRightRadius: 8,
      borderBottomRightRadius: 8,
      borderWidth: 1,
      borderLeftWidth: 0,
      borderColor: colors.border,
      paddingHorizontal: 16,
      paddingVertical: 16,
      fontSize: 16,
      color: colors.text,
      flex: 1,
      minHeight: 48,
    },
    link: {
      color: colors.accent,
      textDecorationLine: "underline",
    },
  });
